#端口号
server:
    port: 8080
spring:
    datasource:
        #驱动类
        driver-class-name: com.mysql.jdbc.Driver
        #数据库url
        url: jdbc:mysql://localhost:3306/library_system?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
        #数据库用户名
        username: root
        #数据库密码
        password:
#自定义配置类
myconfig:
    #分页的大小
    pageSize: 5